def main():
    test_cases = int(input("How many problems to solve?\n"))
    solution = solve_cases([], test_cases)
    print()
    print_solution(solution, test_cases, 0)


def print_solution(solution: list, test_cases: int, pos: int) -> None:
    """Prints the solution generated by the solver recursively"""
    if test_cases > 0:
        print(f"Solution for problem {pos}: {solution[pos]}")
        print_solution(solution, test_cases-1, pos+1)


def solve_cases(solutions: list, num_test_cases: int) -> list:
    """Taking input for the number of test cases provided, and passing it to the solver function"""
    if num_test_cases > 0:
        int_count = int(input("How many numbers to sum?\n"))
        inputs = input("Type in your numbers, use space in-between:\n").split(" ")
        solutions.append(sum_of_squares(0, int_count, inputs))
        num_test_cases -= 1
        return solve_cases(solutions, num_test_cases)
    return solutions


def sum_of_squares(sum_value: int, int_count: int, inputs: list) -> int:
    """Counting the sum of squares, recursively"""
    if int_count > 0:
        number = int(inputs[int_count-1])
        if number > 0:
            sum_value += (number ** 2)
        return sum_of_squares(sum_value, int_count-1, inputs)
    return sum_value


if __name__ == '__main__':
    main()
